### PR TITLE
Adds cmake build test for push and pull_requests, updates readme with build badge

### PR DESCRIPTION
**Pull request by zackees**
Library now builds on ubuntu systems using cmake. This build process will also run on each pull request.

### CODE REVIEW

**Comment by zackees** [comment]
Okay I got auto-building to work correctly with emitting warnings. This PR should be good to go.

Now that warnings are enabled... it looks like there is a bug in the code that's being shown in the build logs. I'll open up a second bug report for that as the fix seems easy enough to fix.

See the build log here:
https://github.com/zackees/arduino-liblame/actions/runs/3699790602/jobs/6267520761

Note that no changes to the source code are in this PR.

**Comment by pschatzmann** [comment]
Hmm, checking the changed files: I am missing your changes to encoder.c

**Comment by zackees** [comment]
It will be the next PR. I wanted to keep the changes separate. I hope you don't mind that I wanted to add a little CI to the repo.

**Comment by zackees** [comment]
Any updates on this? I don't think this is a risky change - no code in lame is being target in this PR.

**Comment by pschatzmann** [comment]
Actually I was waiting for your changes to LAME since I didn't see any added value w/o this

**Comment by zackees** [comment]
It turns out that both my commits (the CMAKE and lame changes) were brought in when in with this pull request completed.

I thought that because they were different commits there would be two different pull requests, but somehow both changes got merged. Please review what went into the repo.

**Pull request merged**
